### ISSUE TITLE
咨询emysql

### ISSUE THREAD

**Issue by ghost** [redink/data_structure_erl#1]
由于在emysql的分支下不能提问，所以发布在这里，见谅。我看到您在emysql里加入连接池管理器，用于解决原来conn_mgr存在的单点问题，我想问这个分之是否已经用于生产环境，在上线过程中有没有问题？是否已经同步到github上来？谢谢。

**Comment by redink** [comment]
https://github.com/toolkit00/Emysql
原来的Emysql 作者已经不维护了，所以我fork了一份出来。
这个版本的Emysql 正在production 环境下使用。连接池管理的，也同步到这个版本下面了：
https://github.com/toolkit00/Emysql/pull/1
另外，我做了一些调整，可见 "Pull requests"。

**Comment by redink** [comment]
github 不方便的话，可以加我QQ 237667802

**Comment by ghost** [comment]
谢谢，我已经同步到toolkit00的emysql的分支版本了
